### ISSUE TITLE
Default download URL for Nomad is broken

### ISSUE THREAD

**Issue by scarolan** [hashicorp/guides-configuration#39] opened 2018-05-30 12:42 UTC
It's fetching this default URL from somewhere, but this doesn't exist:
```
NOMAD_URL=https://releases.hashicorp.com/nomad//nomad__linux_amd64.zip
```

Setting NOMAD_ENT_URL to a valid download URL seems to fix the issue:
```
export NOMAD_ENT_URL=https://releases.hashicorp.com/nomad/0.8.3/nomad_0.8.3_linux_amd64.zip
```

**Comment by bensojona** [comment] 2018-05-30 16:21
@scarolan Hmm, looks like the [`NOMAD_VERSION`](https://github.com/hashicorp/guides-configuration/blob/master/nomad/nomad-aws.json#L14) env var isn't being set - [the version isn't set by default](https://github.com/hashicorp/guides-configuration/blob/master/nomad/scripts/install-nomad.sh#L6). Which build was it?

**Comment by bensojona** [comment] 2018-09-04 03:42
@scarolan - closing this for now as the script is working as intended (requiring the `VERSION` being passed in). Was this happening in one of the provisioning guides or being called elsewhere?

**Closed by bensojona** 2018-09-04 03:42 UTC
